chore: version packages (#703)
This PR was opened by the [Changesets
release](https://github.com/changesets/action) GitHub action. When
you're ready to do a release, you can merge this and the packages will
be published to npm automatically. If you're not ready to do a release
yet, that's fine, whenever you add more changesets to main, this PR will
be updated.


# Releases
## @gram-ai/create-function@0.5.1

### Patch Changes

- cfc187f: We now install the CLI and run gram auth automatically (if
yes is chosen) during pnpm create

## @gram-ai/functions@0.5.1

### Patch Changes

- 6952ee4: Reverted the Gram Functions TS framework template to export
the instance of
`Gram` as the default export in `src/gram.ts`. This makes the
boilerplate code
    work again when deployed.
- 8c3c87c: Allows for creating functions with variables in gram
functions built with mcp passthrough

## cli@0.11.4

### Patch Changes

- b9078f4: Adds support to the Playground for any tool type, notably
enabling function tools to be used there

## dashboard@0.17.4

### Patch Changes

- b9078f4: Adds support to the Playground for any tool type, notably
enabling function tools to be used there
-   Updated dependencies [7afda6e]
    -   @gram/client@0.16.3

## @gram/client@0.16.3

### Patch Changes

- 7afda6e: Allows the MCP metadata map to accept arbitrary value types
as supported by the server

## function-runners@0.1.2

### Patch Changes

- 329264e: Bind `handleToolCall` and `handleResources` to their owning
objects if needed
    in TypeScript runner entrypoint.

When `handleToolCall` and `handleResources` are exported by an object,
ensure
they are bound to that object so that any references to `this` inside
the
function work correctly. This was breaking the Gram TS SDK which does
this:

        const gram = new Gram()
          .tool(/* ... */);

// We were calling gram.handleToolCall without binding it to `gram` in
        // gram-start.mjs
        export default gram;

- a19db7c: Updated function runner images to install the pre-bundled
ca-certificates
    package which allows sub-processes to verify TLS connections.

- 329264e: Remove invalid flush option on named pipe in TypeScript
function runner
entrypoint. Pipes are in-memory "files" and do not support flush
operations. In
production, we were observing errors when trying to flush a named pipe:

        Error: EINVAL: invalid argument, fsync

## server@0.9.7

### Patch Changes

- b9078f4: Adds support to the Playground for any tool type, notably
enabling function tools to be used there
- 7afda6e: Allows the MCP metadata map to accept arbitrary value types
as supported by the server

## gram-template-gram@0.0.1

### Patch Changes

- 6952ee4: Reverted the Gram Functions TS framework template to export
the instance of
`Gram` as the default export in `src/gram.ts`. This makes the
boilerplate code
    work again when deployed.
-   Updated dependencies [6952ee4]
-   Updated dependencies [8c3c87c]
    -   @gram-ai/functions@0.5.1

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>